### ISSUE TITLE
Discussion: Support HTTP instrumentation, custom HTTP transports

### ISSUE THREAD

**Issue by sam-falvo** [rackspace/gophercloud#147]
This blog article has had an impact on my thinking: http://brandur.org/sdk .  I encourage everyone to read it.

In particular, the discussion surrounding HTTP instrumentation is directly relevant to Gophercloud.

Gophercloud presently relies on a package I wrote called Perigee, and while Perigee supports the installation of custom HTTP transports, Gophercloud itself doesn't expose this feature.  Finding the right way to expose this capability will, I think, be useful to have in the future.

Should I create a Perigee V3 API that exists purely as a Go interface and dependency-inject it somehow into Gophercloud?  Or should we rely on Go stdlib's HTTP transports?  There are arguments either way, and this should be an interesting topic of discussion once v0.2.x has been revealed.

**Comment by jrperritt** [comment]
I believe this is closed by #365
