### ISSUE TITLE
Support endpoints with self signed / invalid https certificates

### ISSUE THREAD

**Issue by ghost** [rackspace/gophercloud#158]
I'm using [packer](https://github.com/mitchellh/packer) with the OpenStack Builder which in turn uses gophercloud to talk to the API. We have a local installation of OpenStack and using a selfsigned certificate.

In general it's possible to configure net/http to [disable the security check](http://stackoverflow.com/a/12122718). Any chance to build this into gophercloud as some sort of option? I'm willing to create a pull request if someone could point me to where it would be best to implement?

Thanks!

**Comment by jrperritt** [comment]
As of last week, you can now pass in a [custom HTTP client](https://github.com/rackspace/gophercloud/blob/master/provider_client.go#L62).
