### ISSUE TITLE
Identity V3 not supported

### ISSUE THREAD

**Issue by stenstad** [rackspace/gophercloud#182]
With the Identity v2.0 API marked as deprecated in Icehouse (alltho reverted after release), cloud providers are starting to require using the v3 API to authenticate.

This is needed to support domains, to achieve full multi-tenancy in public clouds.

The v2.0 API seems to be scheduled for removal in the Kilo release next year.

**Comment by jrperritt** [comment]
Implemented here: https://github.com/rackspace/gophercloud/tree/master/openstack/identity/v3

Documentation here: http://gophercloud.io/docs/identity/v3/
