### ISSUE TITLE
Plans going forward for nova-compute based networking (Nebula support)?

### ISSUE THREAD

**Issue by hartzell** [rackspace/gophercloud#313]
Hi All,

I've backed my way into gophercloud while working on @haklop's project to [add openstack support](https://github.com/haklop/terraform) to [terraform](https://github.com/hashicorp/terraform).  My openstack cloud is a Nebula system.

Your recent major-numbered release broke the openstack provider (which is obviously why you made it was a major numbered release...).  @haklop seems to be considering how to move forward; continue to lean on gophercloud or write his own layer.

While chanting "do not reinvent the wheel" I suggested that it would be great to use an existing library and put our energy into new functionality.  If this works, parts of the terraform provider are just shims between gophercloud and the rest of terraform.

*But*, that depends on gophercloud being a reasonable fit.

Putting my money where my mouth is, I've been trying to understand what bits of gophercloud {do,do not} work against my Nebula system.

Following the advice in the README.md, CONTRBUTING.md, and acceptance/README.md (three cheers for documentation that helps newcomers get started!!!) I've gotten to the point where the most basic thing:

```
allons:gophercloud georgewh$ go test -p=1 -tags 'acceptance fixtures' github.com/rackspace/gophercloud/acceptance/openstack
ok  	github.com/rackspace/gophercloud/acceptance/openstack	0.246s
```

seems to work.

When I step it up a level things get a bit more interesting.  After an initial failure in TestBootFromVolume (which is unlikely to be a show stopper), tests PASS for a while before running smack into a stone wall.

```
allons:gophercloud georgewh$ go test -v -p=1 -tags 'acceptance fixtures' github.com/rackspace/gophercloud/acceptance/openstack/compute/...
=== RUN TestBootFromVolume
--- FAIL: TestBootFromVolume (0.37 seconds)
	bootfromvolume_test.go:28: Creating server [Gophercloud-BuM4nwho].
	convenience.go:34: Failure in bootfromvolume_test.go, line 46: unexpected error "Expected HTTP response code [200 202] when accessing URL(http://proxy.nebula.gene.com:8774/v2/6ba254b787054e23a3abe5030f416b4f/os-volumes_boot); got 400 instead with the following body:\n{\"badRequest\": {\"message\": \"Invalid imageRef provided.\", \"code\": 400}}"
=== RUN TestListExtensions
--- PASS: TestListExtensions (0.38 seconds)
[...]
=== RUN TestListServers
--- PASS: TestListServers (0.56 seconds)
	servers_test.go:24: ID	Region	Name	Status	IPv4	IPv6
	servers_test.go:30: ---
	servers_test.go:38: bf035093-9264-48d7-9d58-03b12cb57643	ACPTTESTkceWPaO2eckXKVxE	ACTIVE
	servers_test.go:38: fb92f25c-9851-4047-8580-e8a7003aeabf	ACPTTESTcjinPh26JgGU867E	ACTIVE
	servers_test.go:38: 62efe149-2d7d-4fce-ad55-a073eec28a25	ACPTTESTwIY675Cg5WkBbwGc	ACTIVE
	servers_test.go:38: f1716a70-34d3-40a6-af9c-c6dbd9b8d2c7	ACPTTESTZsbKImFdyeRqR0pZ	ACTIVE
	servers_test.go:38: 7d11555b-f831-43f3-8db6-db71240e2ca0	ACPTTESTjIwguEqXOVlwFQJX	ACTIVE
	servers_test.go:38: 218de8aa-e10a-4f77-b4cb-a0a8e2951bf5	ACPTTESTO537X8aGvEtzfBwP	ACTIVE
	servers_test.go:38: 55721882-bb69-4d4c-a240-77ebb94ed962	ACPTTESTLl4jjYr1y237jbJ0	ACTIVE
	servers_test.go:45: --------
		7 servers listed on 1 pages.
=== RUN TestCreateDestroyServer
--- FAIL: TestCreateDestroyServer (0.42 seconds)
	servers_test.go:74: Unable to create a networking client: No suitable endpoint could be found in the service catalog.
=== RUN TestUpdateServer
--- FAIL: TestUpdateServer (0.40 seconds)
	servers_test.go:74: Unable to create a networking client: No suitable endpoint could be found in the service catalog.
=== RUN TestActionChangeAdminPassword
=== RUN TestActionReboot
=== RUN TestActionRebuild
=== RUN TestActionResizeConfirm
=== RUN TestActionResizeRevert
--- FAIL: TestActionChangeAdminPassword (0.42 seconds)
	servers_test.go:74: Unable to create a networking client: No suitable endpoint could be found in the service catalog.
--- FAIL: TestActionReboot (0.42 seconds)
	servers_test.go:74: Unable to create a networking client: No suitable endpoint could be found in the service catalog.
--- FAIL: TestActionRebuild (0.42 seconds)
	servers_test.go:74: Unable to create a networking client: No suitable endpoint could be found in the service catalog.
--- FAIL: TestActionResizeConfirm (0.42 seconds)
	servers_test.go:74: Unable to create a networking client: No suitable endpoint could be found in the service catalog.
--- FAIL: TestActionResizeRevert (0.43 seconds)
	servers_test.go:74: Unable to create a networking client: No suitable endpoint could be found in the service catalog.
FAIL
exit status 1
FAIL	github.com/rackspace/gophercloud/acceptance/openstack/compute/v2	6.293s
```

It looks like the compute tests, and possibly the functionality, is intertwined with the networking capabilities.

It doesn't [sound like Nebula will be supporting Neutron networking](http://www.enterprisenetworkingplanet.com/datacenter/why-sdn-is-not-needed-for-enterprise-cloud-video.html) anytime soon and many of my use cases fall within the capabilities of nova-compute functionality.

So, finally some questions:

1. Do you have a plan for supporting systems that do not use Neutron networking?

2. Even if you don't implement it yourself, is your design flexible enough to support both Neutron and nova-compute based networking?

3. Is the dependence on networking functionality in servers_test.go necessary/desirable, or is it an bug and the tests should be reworked so that they test server functionality independent of network functionality?

Thanks!

**Comment by devcamcar** [comment]
Great progress, sorry I didn't see this thread sooner.  For nova-network you do not need to supply a network UUID.

**Comment by jrperritt** [comment]
Support has been added for this. Also, #315 is about this same issue. Closing.
