### ISSUE TITLE
Nova Networks (OpenStack)

### ISSUE THREAD

**Issue by jrperritt** [rackspace/gophercloud#315]
Implemented for Rackspace [here](https://github.com/rackspace/gophercloud/tree/master/rackspace/compute/v2/networks), though I think OpenStack offers more operations. Related to #313

**Comment by jtopjian** [comment]
With the merge of #360, I think gophercloud should now fully support nova-network. @hartzell: if there's anything else missing, please let me know and I can look into it.

**Comment by jrperritt** [comment]
Closing. If there's something we missed, we can reopen it.
