### ISSUE TITLE
gophercloud.io domain is misconfigured

### ISSUE THREAD

**Issue by smashwilson** [rackspace/gophercloud#316]
> The page build completed successfully, but returned the following warning:
>
> Your site's custom domain is currently misconfigured. You must take immediate corrective action to ensure that your site remains available. See https://github.com/blog/1917-github-pages-legacy-ip-deprecation for more information. Instructions on updating your site's IP address can be found at https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages, and of course, you can always get in touch with a human at support@github.com. For the more technical minded folks who want to skip the help docs: your site's DNS records are pointed to a deprecated IP address.
>
> For information on troubleshooting Jekyll see:
>
>  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting
>
> If you have any questions please contact us at https://github.com/contact.

Looks like we need to fuss with gophercloud.io.

**Comment by jrperritt** [comment]
This seems to have been fixed.
