### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by Zevran** [rackspace/gophercloud#337]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with gophercloud. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable gophercloud on @Sourcegraph by going to https://sourcegraph.com/github.com/rackspace/gophercloud and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by jrperritt** [comment]
Done  :)

**Comment by Zevran** [comment]
Thank you :)
