### ISSUE TITLE
Get object via temporary URL

### ISSUE THREAD

**Issue by jackspirou** [rackspace/gophercloud#349]
I noticed on https://developer.rackspace.com/docs/cloud-files/getting-started/?lang=go that the section on getting an object via a temporary URL is currently not available.  Im working on an application hosted on Rackspace that would greatly benefit from this feature.

Below is a screen shot of the documentation just for reference:

---
![screen shot 2015-02-01 at 11 53 15 am](https://cloud.githubusercontent.com/assets/5687406/5993068/34115a9e-aa09-11e4-9f5e-4ed25acbb214.png)
---

Any ideas when this feature might be implemented?  I saw it is available in other Rackspace SDKs such as PHP.  Would it be hard to implement? Is it something I might want to take a crack at? 

Any info would be great!  Thanks for supporting a Golang SDK!

**Comment by jrperritt** [comment]
How about tomorrow :)  Thank you for bringing this up; I wasn't aware of it. When the feature gets merged, I'll update the Getting Started docs with sample code.

**Comment by jackspirou** [comment]
Thanks guys for merging this so fast.  I was chatting with our object rocket and rackspace guys today and mentioned how awesome the gophercloud repo is. :)

**Comment by jrperritt** [comment]
You are quite welcome, and thank you again for raising the issue. It's great to know people are using the library :)
