### ISSUE TITLE
Set a custom user agent

### ISSUE THREAD

**Issue by smashwilson** [rackspace/gophercloud#354]
This will help metrics collection, etc.

**Comment by smashwilson** [comment]
Actually, this would dovetail nicely with the centralization of HTTP operations that will be needed for both #147 and #152.

It would also be beneficial to allow clients to easily append to the agent, to add specificity.

**Comment by everett-toews** [comment]
First off http://tools.ietf.org/html/rfc7231#section-5.5.3

Not only do you want to set a custom user agent, you want to give your users the ability to _append_ to that custom user agent. So if your custom user agent is

    gophercloud/1.1.0

Provide a method for your users to easily append their own user agent so they can further customize it.

    gophercloud/1.1.0 docker-machine/0.1.2

This will give us much better insight into how people are using gophercloud. This needs to be part of *any * examples that are written for gophercloud so people just copy/paste it it.
