### ISSUE TITLE
volumeattach extension

### ISSUE THREAD

**Issue by jtopjian** [rackspace/gophercloud#358]
Hello,

I've made an attempt at creating a volumeattach extension. Surprisingly it works :smile: 

https://github.com/jtopjian/gophercloud/commit/520307e97d087e6fc284ad349a44a73d2d5b560b

However, I was wondering if anyone could give it a review and let me know what could be done better. The most obvious area to me is how to better handle the `ServerID`. This parameter is needed in the URL, so I'm wondering if it would be better to:

* Pull the `ServerID` from the option struct and then build the URL
* Pull the `ServerID` from the URL and add it to the option struct

Thanks,
Joe

**Comment by jrperritt** [comment]
After looking at the docs, I think you can delete lines [73](https://github.com/jtopjian/gophercloud/commit/520307e97d087e6fc284ad349a44a73d2d5b560b#diff-085a618482f28067882ed081aa33e868R58) and [58](https://github.com/jtopjian/gophercloud/commit/520307e97d087e6fc284ad349a44a73d2d5b560b#diff-085a618482f28067882ed081aa33e868R58) in the commit above. The server ID should be the same one that gets passed in as a parameter to the functions. So I think `VolumeID` and `Device` are the only parameters you need in the `CreateOpts` and `CreateOptsExt` structures.

Other than that, the code looks great to me.

**Comment by jtopjian** [comment]
That makes sense. I'll go ahead and re-work it and submit a PR.
