### ISSUE TITLE
Rackconnect support

### ISSUE THREAD

**Issue by KevinPike** [rackspace/gophercloud#364]
Ref: http://www.managaedcolocation.net/knowledge_center/article/getting-started-with-the-rackconnect-v30-api

Are there plans to add rackconnect support? I am happy to help.

**Comment by jrperritt** [comment]
Yes and no  :)  We definitely plan on adding RackConnect support in Go, but because it's Rackspace-only, it may go in its own repository (or perhaps a repository of Rackspace-only services) and import Gophercloud packages.
