### ISSUE TITLE
Get object via CDN URL

### ISSUE THREAD

**Issue by jackspirou** [rackspace/gophercloud#371]
The Rackspace documentation at https://developer.rackspace.com/docs/cloud-files/getting-started/?lang=go#get-object-via-cdn-url says that this feature is not currently supported:

```
// Not currently supported by this SDK
```

Screen shot below for reference:

![screen shot 2015-02-15 at 8 12 08 pm](https://cloud.githubusercontent.com/assets/5687406/6206475/4ae39dc0-b550-11e4-985e-2de177c5e5d4.png)

Will this feature be added soon?  Does documentation simply need updating?  

Thanks!

**Comment by jrperritt** [comment]
Oh, yes, you can do that now, but it's a bit manual. This should work:
```
getHeader, err := containers.Get(client, [containerName]).Extract()
if err != nil {
    // error checking...
}
cdnObject := getHeader.CDNUri + "/[objectName]"
```

We should make that a function. I'll do that tomorrow and update the Getting Started Docs.

**Comment by jackspirou** [comment]
Thanks again @jrperritt and @jamiehannaford!
