### ISSUE TITLE
Security group from_group_id doesn't work

### ISSUE THREAD

**Issue by longnguyen11288** [rackspace/gophercloud#374]
Security group rules has [from_group_id](https://github.com/rackspace/gophercloud/blob/master/openstack/compute/v2/extensions/secgroups/requests.go#L182) 

i dont believe this is correct to openstack api. I believe if you want to assign rule to security group you need to set  https://github.com/rackspace/gophercloud/blob/master/openstack/compute/v2/extensions/secgroups/results.go#L54

**Comment by longnguyen11288** [comment]
```
RESP: [200] CaseInsensitiveDict({'date': 'Mon, 16 Feb 2015 19:45:04 GMT', 'content-length': '272', 'content-type': 'application/json', 'x-compute-request-id': 'req-b6a64362-d1b5-4dda-928e-8ed9da7c58a8'})
RESP BODY: {"security_group_rule": {"from_port": 2, "group": {"tenant_id": "f622214bf4a34ababdd03727378ed96f", "name": "cf"}, "ip_protocol": "tcp", "to_port": 3, "parent_group_id": "ade834ad-7177-4c77-b7c2-4a556a9bb458", "ip_range": {}, "id": "40ea807c-82bb-445c-9903-273eaedd3e6c"}}
```
this is post for nova secgroup-add-group-rule

**Comment by jrperritt** [comment]
I'm not sure I understand the issue. `FromGroupID` gets translated to `group_id` in the [Nova security groups API](https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/contrib/security_groups.py#L272).

**Comment by longnguyen11288** [comment]
ah ha! thanks @jrperritt it looks like there was typo or something that lead me to be believe it wasn't working. please review https://github.com/rackspace/gophercloud/pull/375
