### ISSUE TITLE
Printing Applying header [{header}: {value}]

### ISSUE THREAD

**Issue by jackspirou** [rackspace/gophercloud#387]
Hi

I wouldn't call this an issue right yet, but I wanted to ask a question.

I noticed that when uploading files to a container using the `gophercloud` package, a line is printed during runtime.  In my case its expressing that a `X-Auth-Token` header and value is being added.

It looks like this (not an actual X-Auth-Token value):

```
Applying header [X-Auth-Token: 17e92bdad30b0ccc54a34j2l98b52e62]
```

I noticed that it is coming from this method below: 

```Go
func (client *ProviderClient) Request(method, url string, options RequestOpts) (*http.Response, error)
```

I believe the particular place this printing is happening is here: https://github.com/rackspace/gophercloud/blob/ea5b3ff6c5b56c0f342dd19e6a7496779b6c2bb0/provider_client.go#L172

Speaking for myself only, it was confusing watching this printing out during runtime and it took me a couple minutes to track down the source.  Also if your building a CLI binary used for uploading to Rackspace containers (like im thinking of doing) it would disturb the users output.  

I believe we could remove line `172`, but I thought I would ask first, before I submit a pull request :)

Thanks!

**Comment by smashwilson** [comment]
Hah! Yes, this is debugging output that I left in by mistake. PR away :grin:

**Comment by jackspirou** [comment]
Thanks @smashwilson
