### ISSUE TITLE
Map status codes to concrete errors

### ISSUE THREAD

**Issue by smashwilson** [rackspace/gophercloud#401]
I think it would be helpful to map "known error" status codes to concrete Go errors, so that a `Get` call could return `ErrContainerNotFound` instead of the more generic "unexpected status code" error. The benefit to doing this would be that it would be easier for client code to catch common error conditions and recover appropriately -- as another concrete example, it's currently awkward to report when authentication has failed.

**Comment by jrperritt** [comment]
closing due to backwards-incompatibility. this will go in `gophercloud/gophercloud`
