### ISSUE TITLE
RackSpace network returns invalid URL

### ISSUE THREAD

**Issue by Veraticus** [rackspace/gophercloud#420]
I ran into this issue in [Terraform](https://github.com/hashicorp/terraform/issues/1560), but I think it's actually a gophercloud bug.

It seems like NewNetworkV2 will always append a `v2.0/` to any networking URL. For Terraform, at least, this results in URLs of the form `https://iad.networks.api.rackspacecloud.com/v2.0/v2.0/networks` which is unfortunately incorrect.

I suspect the line that does this is https://github.com/rackspace/gophercloud/blob/master/openstack/client.go#L230.

**Comment by jrperritt** [comment]
That's not so much a Gophercloud bug as a quirk of OpenStack. In addition, the Terraform provider you're using is for OpenStack, which in several ways is different than Rackspace (including in authentication, which you've discovered). I have a (not-yet-but-soon-to-be-complete) PR for a Terraform [Rackspace provider](https://github.com/hashicorp/terraform/pull/1438).

**Comment by Veraticus** [comment]
Thanks @jrperritt, I appreciate the clarification!

**Comment by jrperritt** [comment]
Sure :smile: Sorry for the confusion; Many OpenStack services like Neutron actually work as is on the Rackspace cloud, but the authentication schemes are different for some of the services. For example, you can compare the OpenStack Neutron client in the link you pasted to the [Rackspace one](https://github.com/rackspace/gophercloud/blob/master/rackspace/client.go#L176).

**Comment by Veraticus** [comment]
Not your fault! It is a tragedy that Terraform doesn't support RackSpace yet... but it looks like your PR is pretty far along so hopefully it'll be in soon.
