### ISSUE TITLE
nil pointer dereference

### ISSUE THREAD

**Issue by gfrey** [rackspace/gophercloud#427]
https://github.com/rackspace/gophercloud/blob/master/openstack/objectstorage/v1/objects/requests.go#L138

In this line resp.Body is read. The gophercloud.ServiceClient returns "nil, err" in the error case, aka this will fail miserably. Better check for the error, like:
~~~
res.err = err
if resp != nil {
  res.Body = resp.Body
  res.Header = resp.Header
}
~~~

**Comment by jrperritt** [comment]
Indeed, I think all the Object Storage requests need to be updated.
