### ISSUE TITLE
connection reset by peer error in objects.Create when uploading objects to swift

### ISSUE THREAD

**Issue by rak1988** [rackspace/gophercloud#450]
I am uploading a 300MB directory with not more than 50 MB files. Sometimes it hangs and throws out an error that connection reset by peer. Sometimes it is successful. Can you please help me out with this error ?

**Comment by rak1988** [comment]
I am pushing the files to swift

**Comment by rak1988** [comment]
we are using softlayer object storage

**Comment by rak1988** [comment]
This the logs trace I am getting:

2015/07/29 10:40:49 /home/rakesh/workspace1/sample/src/server.go:409: Put http://dal05.objectstorage.softlayer.net/v1/AUTH_<Authid here>/rak2-57f9feee9a92df1d663b269ffddc278b0fcf123e/root/test/data3/messages-20150712: write tcp 173.192.119.146:80: connection reset by peer
panic: Put http://dal05.objectstorage.softlayer.net/v1/AUTH_<Auth id here>/root/test/data3/messages-20150712: write tcp 173.192.119.146:80: connection reset by peer

goroutine 22 [running]:
log.Panic(0xc209a2bb88, 0x1, 0x1)
	/usr/local/go/src/log/log.go:307 +0xb9
main.Worker(0x9, 0xc208040120, 0xc2080406c0, 0xc20924ae00, 0x33, 0xc208ae0566, 0x23, 0xc209276120, 0x23, 0xc2081bf285, ...)
	/home/rakesh/workspace1/sample/src/server.go:409 +0xeab

goroutine 1 [IO wait, 6 minutes]:
net.(*pollDesc).Wait(0xc208010220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080101c0, 0x0, 0x7f909c954bb0, 0xc20800b278)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036060, 0x57bb0e, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208036060, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc208040180, 0x7f909c956028, 0xc208036060, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc208040180, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc20800b1f8, 0x6, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1808 +0xba
main.startServer()
	/home/rakesh/workspace1/sample/src/server.go:949 +0x757
main.main()
	/home/rakesh/workspace1/sample/src/server.go:958 +0x1b

**Comment by rak1988** [comment]
Did anyone see this error before ? Any leads to this would be very helpful. Thank you !

**Comment by guanglinlv** [comment]
@rak1988 

do you use terraform with openstack? the library of openstack SDK used by terraform has a connection  reuse issue, maybe this cause that problem;  [gophercloud/issues#465](https://github.com/rackspace/gophercloud/issues/465)

thanks.

**Comment by jrperritt** [comment]
closing. the fix above has been merged. other than that, this looks like something that can be solved with either a custom `http.Client` or on the back-end.
