### ISSUE TITLE
Support for lbaasv2

### ISSUE THREAD

**Issue by jgriffiths1993** [rackspace/gophercloud#460]
Would be nice to have support for LBaaS API v2

**Comment by jgriffiths1993** [comment]
I'm working on this, finally

**Comment by vipulsabhaya** [comment]
@jgriffiths1993 any update on this? we'd like to help push this through

**Comment by vipulsabhaya** [comment]
@jrperritt Do you have any info on the status of this issue?

**Comment by jrperritt** [comment]
>> Do you have any info on the status of this issue?

I don't, and I haven't seen any work on it.

**Comment by dagnello** [comment]
I am starting work on this.

**Comment by jrperritt** [comment]
closed by #575
