### ISSUE TITLE
Migrate to /gophercloud organization

### ISSUE THREAD

**Issue by jnoller** [rackspace/gophercloud#462]
We've discussed this - but I figure a public issue tracking it / timelines / et al would be good. As gophercloud has first class openstack support, we want to move it out of the /rackspace namespace and break out the vendor bits to allow for a more open community and guidelines on how to plug in vendor support/extensions (those could live under the org too). I set up https://github.com/organizations/gophercloud/ 

This is a tracker bug

**Comment by berendt** [comment]
I want to propose to move this project into the OpenStack organization (https://github.com/openstack) and to use the common development workflows of OpenStack. This way we can consume the existing OpenStack infrastructure (e.g. the Gerrit for code reviews or there Jenkins to run test jobs). What do you think about it?

**Comment by jnoller** [comment]
@berendt we've discussed this at length, with inside and outside contributors and agreed that non python, open source SDKs should use the tools and contribution model most appropriate for them. In the case of gophercloud and other go utilities that is the default git/github workflow and packaging within the ecosystem.

@annegentle (TC), @everett-toews and other sdk and ecosystem authors and openstack contributors agree. Jclouds, fog, and many other SDKs that build up the openstack ecosystem use the tooling and processes native to their communities.

**Comment by berendt** [comment]
@jnoller Thanks for the explanation.

**Comment by annegentle** [comment]
Thanks @berendt for discussing here too. I'm personally advocating for a huge happy festival field outside of the OpenStack big tent where all these ecosystem tools dance happily. :dancers: Go and Gophercloud are ecosystem as are the others - Java/jclouds, Ruby/fog. Thanks for asking.

**Comment by jrperritt** [comment]
[gophercloud/gophercloud](https://github.com/gophercloud/gophercloud)

The library is currently unstable pending feedback, but is up-to-date with this library.
