### ISSUE TITLE
[SOLVED]GET EOF on servers.get

### ISSUE THREAD

**Issue by guanglinlv** [rackspace/gophercloud#465]
Hi,

when I use `s, err := servers.Get(client, instanceID).Extract()` to refresh server status multiple times, i always get the error at the eighth times.

the error message is so puzzled ::)
```
Get http://xxx:8774/v2/16d0657471124a8da827347ade4630cd/servers/f9b7571a-a92a-417f-845a-eba13f5e6338: EOF
```

thanks.

**Comment by guanglinlv** [comment]
Hi,

I got the reason, it is a bug of golang http pool), golang will try to reuse the connection for `http.client.Do`. but the connection maybe broken by `haproxy stats connection` of openstack. golang does not fix it  currently.a workaround is close the connection immediately when we got the Response. maybe add line `req.Close = true` before [provider_client.go#L181](https://github.com/rackspace/gophercloud/blob/fab1f3d270f58c199398e892c2c9c234fe2147d8/provider_client.go#L181)

more details : 
[golang/go#8946](https://github.com/golang/go/issues/8946)
[golang/go#4677](https://github.com/golang/go/issues/4677)

**Comment by jrperritt** [comment]
Thank you for filing this. I think a fix has been merged.
