### ISSUE TITLE
Infinite recursion with AllowReauth

### ISSUE THREAD

**Issue by marcin-ptaszynski** [rackspace/gophercloud#498]
Hi guys,

It's possible to cause client to run infinite recursion (or until it hits file descriptor limit) during [Reauth Attempt](https://github.com/rackspace/gophercloud/blob/d86f9582b08d56dc9422e3a5d9f120b117487427/provider_client.go#L187-L195), it receives 401 response. Below code uses v2 identity API, but the same happens when we use `github.com/rackspace/gophercloud/openstack/identity/v3/tokens` `Get()`

```
package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"

	"github.com/rackspace/gophercloud"
	"github.com/rackspace/gophercloud/openstack"
)

func main() {
	opts := gophercloud.AuthOptions{
		IdentityEndpoint: "http://keystone-host:5000/v2.0",
		Username:         "user",
		Password:         "pass",
		TenantName:       "admin",
		AllowReauth:      true,
	}

	providerClient, err := openstack.AuthenticatedClient(opts)
	if err != nil {
		panic(err)
	}

	serviceClient := openstack.NewIdentityV2(providerClient)

	stdin := bufio.NewReader(os.Stdin)

	for {
		fmt.Println("<<<<")

		byteToken, _, err := stdin.ReadLine()
		if err != nil {
			panic(err)
		}
		token := string(byteToken)
		fmt.Printf(".... \"%s\"\n", token)

		var result interface{}
		_, err = serviceClient.Get(serviceClient.ServiceURL("tokens", token), &result, &gophercloud.RequestOpts{
			OkCodes: []int{200, 203},
		})
		if err != nil {
			fmt.Println("error: ", err)
		}

		json, _ := json.MarshalIndent(result, "", "  ")
		fmt.Println(">>>>", string(json))
	}
}
```

In order to reproduce
* change user password in the middle of execution
* write to stdin token from different domain (v3), etc

In each case client takes up all fd and doesn't close them even after error
`(Error trying to re-authenticate: * a lot)Error trying to re-authenticate: Error trying to re-authenticate: Error trying to re-authenticate: Error trying to re-authenticate: Error trying to re-authenticate: Error trying to re-authenticate: Error trying to re-authenticate: Error trying to re-authenticate: Error trying to re-authenticate: Error trying to re-authenticate: Post http://10.33.5.214:5000/v2.0/tokens: dial tcp 10.33.5.214:5000: too many open files`
 is returned.

**Comment by jrperritt** [comment]
Indeed you're right; that's quite possible. The way to limit the number of attempts is to provide a custom client to the [provider client](https://github.com/rackspace/gophercloud/blob/master/provider_client.go#L62) and provide a transport that implements the `RoundTripper` interface and [stores the number of failed retries](https://github.com/rackspace/rack/blob/master/auth/clients.go#L309-L313). 

We do it in the Rackspace CLI [here](https://github.com/rackspace/rack/blob/master/auth/clients.go#L350-L355).

**Comment by marcin-ptaszynski** [comment]
Thank you very much. It worked as you've described.
