### ISSUE TITLE
Unit tests failing with Go import error

### ISSUE THREAD

**Issue by tpot** [rackspace/gophercloud#507]
Hi there.  I'm trying to run the unit tests for gophercloud and they are failing with a Go import error:

```
$ cd openstack/common/extensions
$ go test .
# github.com/rackspace/gophercloud/openstack/common/extensions
./requests_test.go:14: undefined: HandleListExtensionsSuccessfully
./requests_test.go:22: undefined: ExpectedExtensions
./requests_test.go:33: undefined: HandleGetExtensionSuccessfully
./requests_test.go:37: undefined: SingleExtension
FAIL	github.com/rackspace/gophercloud/openstack/common/extensions [build failed]
```
This happens in a bunch of other places in the codebase.

Apologies if this is a silly noob question but I'm pretty new to Go.

Thanks!

Tim.

**Comment by jrperritt** [comment]
Ah, sorry, I think our documentation was out of data. You can run `script/unittest` or 
`go test -tags=fixtures ./...`

**Comment by tpot** [comment]
A belated thanks for the suggestion - adding "-tags=fixtures" to my test invocation works fine.
