### ISSUE TITLE
Cinder apiversion.List() calls incorrect API path

### ISSUE THREAD

**Issue by marcin-krolik** [rackspace/gophercloud#533]
In BlockStorage V1 **requests.go**
```go
apiversions.List(c *gophercloud.ServiceClient) pagination.Pager {...}
```
there is a call to listURL() function from **urls.go**
```go
func listURL(c *gophercloud.ServiceClient) string {
	return c.ServiceURL("")
}
```
Above function returns full service URL which is in form **scheme://host:port/path** where **path** contains version and tenant id (example:. "/v1/3a02ee0b5cf14816b41b17e851d29a94")
This leads to incorrect REST call, as according to documentation list of available API version is located at root path for both V1.0 and V2.0.

Proposed solution:
```go
func listURL(c *gophercloud.ServiceClient) string {
        u, _ := url.Parse(c.ServiceURL(""))
	u.Path = "/"
	return u.String()
}
```

**Comment by jrperritt** [comment]
closed by #535
