### ISSUE TITLE
Enhancement request: Extend router code to accept value_specs like Heat does

### ISSUE THREAD

**Issue by VMTrooper** [rackspace/gophercloud#539]
OpenStack clouds running on VMware infrastructure require an exclusive router type for LBaaS to work.

I can create an exclusive router in Heat using the value_specs attribute.

Example:
    acme_router:
      type: OS::Neutron::Router
      properties:
        external_gateway_info: { network: EXTNET }
        value_specs:
          { "router_type": "exclusive" }

At the CLI, the analogous syntax would be: neutron router-create --router_type=exclusive lbaas_router

Is it possible that gophercloud can be updated to support such an attribute?

If it is currently possible, can someone share an example syntax? I tried examining the code, but couldn't see a way to do this.

**Comment by jrperritt** [comment]
>> Is it possible that gophercloud can be updated to support such an attribute?

Currently, no. However, see my comment [I think about this very feature] [here] (https://github.com/rackspace/gophercloud/pull/526#issuecomment-187576990) on how to fix it.

**Comment by VMTrooper** [comment]
Thank you for the update. I will follow the progress on the other link you posted and close this issue.

Thank you for checking out my blog. Cool to see people are referencing it. :-)
