### ISSUE TITLE
support os-quota-set endpoint

### ISSUE THREAD

**Issue by dangogh** [rackspace/gophercloud#540]
Add support for /v2.1/​{admin_tenant_id}​/os-quota-sets/​{tenant_id}​/detail endpoint.  I'm just learning what that entails -- guidance is welcome..

**Comment by jrperritt** [comment]
Have a look at [the contributing guide](https://github.com/rackspace/gophercloud/blob/master/CONTRIBUTING.md) and some of the other [`compute` extensions](https://github.com/rackspace/gophercloud/tree/master/openstack/compute/v2/extensions) to see some example implementations (especially the `List` functions for `SinglePageBase`, like [here](https://github.com/rackspace/gophercloud/blob/master/openstack/compute/v2/extensions/keypairs/results.go#L32)). I can answer any questions you have along the way.

**Comment by dangogh** [comment]
thanks for the tips..   I'd read the contributing guide (hence the [wip]
issue..) and started along the lines you suggested.  Hopefully I'll get up
to speed pretty quickly...  -dan

**Comment by jrperritt** [comment]
The `[WIP]` prefix is for pull request titles.

**Comment by dangogh** [comment]
The documentation for os-quota-set here shows only a GET .../detail endpoint.  Is there documentation elsewhere on the endpoint without /detail? http://developer.openstack.org/api-ref-compute-v2.1.html#listDetailQuotas

**Comment by jrperritt** [comment]
closed by #542
