### ISSUE TITLE
[compute]How can i dynamically add nic equipment（neutron port）to server.

### ISSUE THREAD

**Issue by yuzhihai08** [rackspace/gophercloud#543]
After the success of the virtual machine to create, add network equipment to the virtual machine.

**Comment by jrperritt** [comment]
Have a look at the [`routers`](https://github.com/rackspace/gophercloud/blob/master/openstack/networking/v2/extensions/layer3/routers/requests.go), [`networks`](https://github.com/rackspace/gophercloud/blob/master/openstack/networking/v2/networks/requests.go), and [`ports`](https://github.com/rackspace/gophercloud/blob/master/openstack/networking/v2/ports/requests.go) packages.
