### ISSUE TITLE
Error connecting - EOF error returned

### ISSUE THREAD

**Issue by fatmcgav** [rackspace/gophercloud#551]
I'm trying to use Gophercloud to connect to a new Openstack cloud. 

However I appear to be hitting issues with the connection failing with 'EOF'.

I've tried to simplify things and write a stand-alone go test that just attempts to auth, and it shows the same behaviour, so think this is a Go issue rather than Gophercloud specifically... 

However thought I'd ask here in-case anyone has any ideas... 

The simple client I've written is:
https://gist.github.com/fatmcgav/35d1a4fbd74c7208f445c487f756a5e1

Any ideas?

Cheers
Gavin

**Comment by jrperritt** [comment]
>> Any ideas?

Not really, other than to say it doesn't look like a Gophercloud issue. I suspect `EOF` is due to the server closing the connection. If you need to deal with TLS or a proxy (custom transport), you can set an `http.Client` for the `ProviderClient.HTTPClient` field.

**Comment by fatmcgav** [comment]
@jrperritt Yeh, in the end tracked the issue down to the end-point only supporting TLS v1.2 and 3 cipher suites, none of which are natively supported by GoLang... 

Issue raised against GoLang, see https://github.com/golang/go/issues/15487

Cheers

**Comment by akutz** [comment]
Ha! I just solved this for the same thing for ScaleIO. My function name was just the same as yours in golang/go#15487. I guess it's not a stretch to call it `macSHA256` though...
