### ISSUE TITLE
panic using server.ListAddresses(...).AllPages()

### ISSUE THREAD

**Issue by dangogh** [rackspace/gophercloud#566]
NOTE:  I have a commit which adds a test for this error and checks the type assertion to panic with more detail.  I'll submit a PR if requested..

trying to get list of addresses from servers,  I did something like this:
```go
       p, err := ListAddresses(client, myserver.ID).AllPages()
       addrs, err := ExtractAddresses(p)
```
I get the following panic:
```
panic: interface conversion: interface is map[string]interface {}, not []interface {} [recovered]
	panic: interface conversion: interface is map[string]interface {}, not []interface {}
goroutine 151 [running]:
panic(0x3f8c40, 0xc820013c80)
...
github.com/rackspace/gophercloud/pagination.Pager.AllPages.func1(0xb88530, 0xc82008abe0, 0x0, 0x0, 0x0)
	/Users/dank/Code/src/github.com/rackspace/gophercloud/pagination/pager.go:156 +0x279
```

**Comment by jrperritt** [comment]
Confirmed. Working on a fix now.

**Comment by jrperritt** [comment]
@dangogh can you `go get -u github.com/rackspace/gophercloud` and confirm this has been fixed?

**Comment by dangogh** [comment]
That was quick :-)   Confirmed..   Thanks!

**Comment by jrperritt** [comment]
Thank you for filing the bug :)
