### ISSUE TITLE
Acceptance tests not running

### ISSUE THREAD

**Issue by dagnello** [rackspace/gophercloud#576]
It looks like acceptance tests are not running:

- https://travis-ci.org/rackspace/gophercloud/jobs/130463218#L356

- https://travis-ci.org/rackspace/gophercloud/jobs/130463219#L354

- https://travis-ci.org/rackspace/gophercloud/jobs/130463220#L362

looks related to:
https://groups.google.com/forum/#!topic/golang-nuts/lunXqaTYuY0

**Comment by jrperritt** [comment]
Travis doesn't run the acceptance tests; they require creating real cloud infrastructure which (potentially) costs time and money.
