### ISSUE TITLE
Reauth Header Problem

### ISSUE THREAD

**Issue by reaperhulk** [rackspace/gophercloud#583]
When defining a ReauthFunc (or using the one provided by AllowReauth) the request that actually triggers the reauth never succeeds. For example, if you call [Download](https://github.com/rackspace/gophercloud/blob/master/openstack/objectstorage/v1/objects/requests.go#L116-L147) with an expired token it will do the following:
* Call `AuthenticatedHeaders` and then set that as the value of `MoreHeaders` in the `RequestOpts` struct. 
* Call the [Request](https://github.com/rackspace/gophercloud/blob/master/provider_client.go#L126) function, which sets the `X-Auth-Token` header itself, but then has it overwritten by the value in `MoreHeaders`.
* Since the token is expired `http.StatusUnauthorized` will be received as a status code and the reauth func will be triggered
* The reauth func will set a new `TokenID` in the struct.
* Now that the new token is set `client.Request(method, url, options)` is recursively called... which sets the new `X-Auth-Token` properly, but then has it overwritten by `MoreHeaders` so the request fails again, triggering another loop.

**Comment by jrperritt** [comment]
Ah, those `AuthenticatedHeaders` calls in the `requests.go` files were all supposed to be removed in favor of the one in `provider_client.go`. Will fix today.

**Comment by reaperhulk** [comment]
Thanks for the quick response @jrperritt, I look forward to the fix :)

**Comment by jrperritt** [comment]
@reaperhulk You `go get -u github.com/rackspace/gophercloud` to get the fix that was just pushed. I'll leave this open until we can confirm that it's been resolved.

**Comment by reaperhulk** [comment]
Yep, this fixes my issue. A quick grep of the codebase looks like you might have missed one last AuthenticatedHeaders call though: `rackspace/objectstorage/v1/cdncontainers/requests.go`

**Comment by jrperritt** [comment]
quite right: #585
