### ISSUE TITLE
Support authentication with trustee user

### ISSUE THREAD

**Issue by strigazi** [rackspace/gophercloud#604]
Our use case is that we want create openstack/cinder volumes using rexray by using a trustee user. To support it, we need the trust_id into scope:
https://github.com/rackspace/gophercloud/blob/master/openstack/client.go#L173

**Comment by josecastroleon** [comment]
Under my point of view, if there is no tenant_id nor tenant_name but there is a trust_id, then you create a scope with only the trust_id

**Comment by josecastroleon** [comment]
https://specs.openstack.org/openstack/keystone-specs/api/v3/identity-api-v3-os-trust-ext.html#consuming-a-trust

**Comment by strigazi** [comment]
Duplicate of #581
